experiment_name: "run_001"

training:
  num_epochs: 100
  batch_size: 64
  learning_rate: 0.0001
  device: "cuda"  # Change to "cpu" if needed
  early_stopping_patience: 10

model:
  input_size: 18
  hidden_size_1: 128
  hidden_size_2: 64
  hidden_size_3: 32
  output_size_score: 1
  output_size_status: 1
  dropout: 0.3

data:
  train_path: "/mnt/d/torch-playground/data/processed/loan_train.csv"
  val_path: "/mnt/d/torch-playground/data/processed/loan_val.csv"
  test_path: "/mnt/d/torch-playground/data/processed/loan_test.csv"
  shuffle: true
  target_status: 'remainder__loan_status'
  target_score: 'min_max_scaler__credit_score'

logging:
  tensorboard_log_dir: "/mnt/d/torch-playground/runs" 
  checkpoint_dir: "/mnt/d/torch-playground/checkpoints"
